backend:
  name: github
  repo: michael-alexei/michael-investment-club
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://michaelinvestmentclub.com"
display_url: "https://michaelinvestmentclub.com"

collections:
  - name: "posts"
    label: "Market Insights"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["date", "title"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", time_format: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "posts" }
      - { label: "Body", name: "body", widget: "markdown" }
